### ISSUE TITLE
permission to use

### ISSUE THREAD

**Issue by kiebor** [ebbypeter/Archimate-PlantUML#7]
would love to include your macros here:
https://github.com/kiebor/PlantUml-Language-Service

It's very similar to the proposal I set out for plantuml archimate syntax early on:

- https://github.com/plantuml/plantuml/files/1092145/archimate.txt
- https://github.com/plantuml/plantuml/issues/61

Thanks in advance.

**Comment by kiebor** [comment]
See modified version of your macros:
https://raw.githubusercontent.com/kiebor/PlantUml-Language-Service/master/src/Macros/archimate.macro

**Comment by ebbypeter** [comment]
feel free to use it... 👍
